on: push
jobs:
  BUILD:
    runs-on: ubuntu-latest
    env:
      $JENKINS_URL: "${{ secrets.JENKINS_URL }}"
      $JENKINS_USER: "${{ secrets.JENKINS_USER }}"
      $JENKINS_API_TOKEN: "${{ secrets.JENKINS_API_TOKEN }}"
    steps:
      - run: |          
          echo "URL: ${{ vars.JENKINS_URL }}"
           echo "USER: ${{ vars.JENKINS_USER }}"
            echo "TOKEN: ${{ vars.JENKINS_API_TOKEN }}"
